blank_issues_enabled: false
contact_links:
  - name: Starbound Community Support
    url: https://community.playstarbound.com/forums/support/
    about: Please ask and answer questions here regarding general Starbound support.
  - name: AbsoluteXeroEX on Starbound Community
    url: https://community.playstarbound.com/members/absolutexero.345894/
    about: Have a question about the mod that you want to ask me in private? Message me on the community forums!
