name: Vanta Race - RePAK

on: [push, pull_request, workflow_dispatch]
jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: ( cd tests/json-syntax && npm install )
        
      - name: Run NPM Test
        run: ( cd tests/json-syntax && npm test )

  check-unoptimized-png:
    if: ${{ github.base_ref || github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y optipng
      - run: .github/scripts/check-png-images.sh

  pack-for-dl:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove unneeded paths & files in PAK file (i.e., ".git", ".disabled")
        run: rm -rf .git .disabled

      - uses: edwardspec/github-action-pack-starbound-mod@v1
        with:
          outputFileName: vanta-race.pak
      - name: Add .pak file to release
        uses: softprops/action-gh-release@v1
        with:
          files: vanta-race.pak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
